# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Our Sunday Supplication"
description: > # this means to ignore newlines until "email:"
   Our Sunday Supplication

email: pcallah1@emporia.edu
#blog logo
logo: "/assets/images/chalice.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/ArchCrest.jpg"

name: 'Patrick Callahan'
author: 'Patrick Callahan'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://SchoolOfHope.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@P_RoryCallahan'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/P_RoryCallahan
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/PRoryCallahan
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
